Lesson 5
ryawych20/javascript pull request #5
Opened 2021-03-08 16:18 UTC by ryawych20

2021-03-14 19:35 UTC, Om1X requested changes

2021-03-14 19:35 UTC, Om1X commented on lesson_5/script.js
> +    totalAmount: 0,
эти свойства излишни, эти значения должны считаться через методы

2021-03-14 19:35 UTC, Om1X commented on lesson_5/script.js
> +        this.calculate();
this.calculate не нужен

2021-03-14 19:35 UTC, Om1X commented on lesson_5/script.js
> +    },
разбить на 2 метода, которые возвращают посчитанное значение

2021-03-15 04:52 UTC, ryawych20 commented on lesson_5/script.js
> +        this.calculate();
Убрал

2021-03-15 04:52 UTC, ryawych20 commented on lesson_5/script.js
> +    },
Разбил на два метода

2021-03-15 05:58 UTC, ryawych20 commented on lesson_5/script.js
> +    totalAmount: 0,
Убрал

2021-03-18 07:28 UTC, merged